# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/bramble/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),bramble)

$(call add-radio-file-sha1-checked,radio/abl.img,93a8f2b99e0a1a84b890eb6903d352c774192974)
$(call add-radio-file-sha1-checked,radio/aop.img,47b10e2aff1099c66867efd18e8ff5f51e84466c)
$(call add-radio-file-sha1-checked,radio/devcfg.img,6637e53241aed07975e6b4ad16b3b541e91be387)
$(call add-radio-file-sha1-checked,radio/featenabler.img,db46a7d2d5a0ee07e94534ca848327009966aa6e)
$(call add-radio-file-sha1-checked,radio/hyp.img,3a3907f074b088fd6bfd4f0c8e00a132a570c24c)
$(call add-radio-file-sha1-checked,radio/keymaster.img,ff20ba01830713a6a8574c07290ebfd18a25e79e)
$(call add-radio-file-sha1-checked,radio/modem.img,7a5a5fda473db1636599f831a1a705e6d4937c06)
$(call add-radio-file-sha1-checked,radio/qupfw.img,3fb32aaed717fc04f0e374053e7f647d3e14691f)
$(call add-radio-file-sha1-checked,radio/tz.img,31fe8de46dfdc0409c13b3801b2c35438bae732d)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,5b000251cd736af706e5196e4bcbc1f1c0f2a873)
$(call add-radio-file-sha1-checked,radio/xbl.img,4230b81fdbf5926984be1534140b2187a050c796)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,ab337d472277c254cf5fc44764c289c2f0fc99c8)

endif
